name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest test_app.py

      - name: Docker Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd:latest

  deploy:
    needs: build-test-docker
    runs-on: ubuntu-latest
    steps:
      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > key.pem
          chmod 400 key.pem

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d -p 80:5000 --name flask-app ${{ secrets.DOCKER_USERNAME }}/flask-ci-cd:latest
          EOF
